### ISSUE TITLE
[Bug] Not running on win10 64bit

### ISSUE THREAD

**Issue by assian** [Suwayomi/Suwayomi-Server#127] opened 2021-06-02 18:27 UTC
my pc is running on win10 64bit
i used this version "Tachidesk-v0.3.0-r388-win32" - still works
i using this version "Tachidesk-v0.4.2-r645-win64 "

Sorry for my poor english :)

i tried every thing for run to app !
Electron Launcher :  not work
Browser Launcher : not work
Debug Launcher : not work

i use debug  this is result :

```
21:12:24.884 [main] ←[34mINFO ←[0;39m suwayomi.server.ServerSetup - Running Tachidesk v0.4.2 revision r645
21:12:25.809 [main] ←[34mINFO ←[0;39m suwayomi.server.util.AppMutex - Mutex status is clear, Resuming startup.
21:12:25.809 [main] ←[34mINFO ←[0;39m xyz.nulldev.androidcompat.bytecode.ModApplier - Applying Javassist mods...
21:12:26.186 [main] ←[34mINFO ←[0;39m suwayomi.server.database.migration.lib.RunMigrations - Running migrations on database jdbc:h2:C:\Users\Burak\AppData\Local\Tachidesk/database
21:12:26.451 [main] ←[34mINFO ←[0;39m suwayomi.server.database.migration.lib.RunMigrations - Database version before migrations: 1
21:12:26.451 [main] ←[34mINFO ←[0;39m suwayomi.server.database.migration.lib.RunMigrations - Running migration version 2: ChapterTableIndexRename
Exception in thread "main" org.jetbrains.exposed.exceptions.ExposedSQLException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "NUMBER_IN_LIST" not found; SQL statement:
ALTER TABLE CHAPTER ALTER COLUMN NUMBER_IN_LIST RENAME TO INDEX [42122-200]
SQL: [ALTER TABLE CHAPTER ALTER COLUMN NUMBER_IN_LIST RENAME TO INDEX]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:49)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:91)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:82)
        at org.jetbrains.exposed.sql.Transaction.exec$default(Transaction.kt:82)
        at suwayomi.server.database.migration.M0002_ChapterTableIndexRename.run(M0002_ChapterTableIndexRename.kt:19)
        at suwayomi.server.database.migration.lib.RunMigrationsKt$runMigrations$$inlined$forEach$lambda$1.invoke(runMigrations.kt:51)
        at suwayomi.server.database.migration.lib.RunMigrationsKt$runMigrations$$inlined$forEach$lambda$1.invoke(runMigrations.kt)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:173)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:194)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:193)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:151)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:123)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:121)
        at suwayomi.server.database.migration.lib.RunMigrationsKt.runMigrations(runMigrations.kt:50)
        at suwayomi.server.database.migration.lib.RunMigrationsKt.runMigrations$default(runMigrations.kt:33)
        at suwayomi.server.database.DBManagerKt.databaseUp(DBManager.kt:31)
        at suwayomi.server.ServerSetupKt.applicationSetup(ServerSetup.kt:92)
        at suwayomi.MainKt.main(Main.kt:14)
        at suwayomi.MainKt.main(Main.kt)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "NUMBER_IN_LIST" not found; SQL statement:
ALTER TABLE CHAPTER ALTER COLUMN NUMBER_IN_LIST RENAME TO INDEX [42122-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:205)
        at org.h2.message.DbException.get(DbException.java:181)
        at org.h2.table.Table.getColumn(Table.java:719)
        at org.h2.command.Parser.columnIfTableExists(Parser.java:8052)
        at org.h2.command.Parser.parseAlterTableAlter(Parser.java:7712)
        at org.h2.command.Parser.parseAlterTable(Parser.java:7698)
        at org.h2.command.Parser.parseAlter(Parser.java:6983)
        at org.h2.command.Parser.parsePrepared(Parser.java:887)
        at org.h2.command.Parser.parse(Parser.java:843)
        at org.h2.command.Parser.parse(Parser.java:815)
        at org.h2.command.Parser.prepareCommand(Parser.java:738)
        at org.h2.engine.Session.prepareLocal(Session.java:657)
        at org.h2.engine.Session.prepareCommand(Session.java:595)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1154)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.prepareStatement(JdbcConnectionImpl.kt:58)
        at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:24)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:47)
        ... 22 more
```

**Comment by assian** [comment] 2021-06-02 18:36
Sorry i foget write this . before runnig new app i delete this folder "C:\Users\<Account>\AppData\Local\Tachidesk" on my pc

**Comment by AriaMoradi** [comment] 2021-06-03 19:16
duplicate of #119, closing

**Closed as completed by AriaMoradi** 2021-06-03 19:16 UTC
Labels: bug
